/* getopttest.c -- program to demonstrate the standard getopt() function
 *		   for processing command line switches
 */

#define _POSIX_C_SOURCE 200809L
#define _ISOC99_SOURCE
#define _XOPEN_SOURCE 700
#define __EXTENSIONS__

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

/* to portably enable error messages generated by getopt(), do both:
 * 1)	comment out the line: opterr = 0;
 * 2)	remove the first colon in the definition of OPTIONS
 */

#define OPTIONS ":hvipl:f:"
#define WHITE_SPACE " \n\r\t\v\f"
#define VERBOSE			0x0001
#define CASE_INSENSITIVE	0x0002
#define PAGING			0x0004

/* prints name of an option and its value as ON/OFF */
void
print_flag(unsigned int flags, unsigned int this_one, char *name)
{
	printf("\t%19s: %s\n", name, (flags & this_one) ? "ON" : "OFF");
}	/* print_flag */

/* Scans the string pointed to by optarg and tries to convert it to a number.
 * Returns 0 if successful (and stores the number in result),
 *	  -1 on any error (prints an error message and leaves result unchanged)
 */
int
scan_switch_number(int switch_char, int *result)
{
	int temp, retval;
	char *ptr;

	errno = 0;
	temp = strtol(optarg, &ptr, 10);
	if (errno != 0  ||  ptr == optarg  ||
	   strspn(ptr, WHITE_SPACE) != strlen(ptr)) {
		fprintf(stderr,"Illegal numeric value \"%s\" for switch -%c\n",
			optarg, switch_char);
		retval = -1;
	} else {
		*result = temp;
		retval = 0;
	}
	return retval;
}	/* scan_switch_number */

int
main(int argc, char *argv[])
{
	unsigned int flags;
	int line_length, c;
	char *output_file_name;

	/* initialize all the options to their default values */
	flags = PAGING;	/* default is that paging will be done */
	line_length = 0;
	output_file_name = NULL;

	/* process all the command line switches */
	opterr = 0;	/* prevent getopt() from printing error messages */
	while ((c = getopt(argc, argv, OPTIONS)) != -1) {
		switch (c) {
		case 'h':	/* print help info */
			printf("-h: this help information\n");
			printf("-v: turn verbose output ON (default OFF)\n");
			printf("-i: turn case sensitivity ON (default OFF)\n");
			printf("-p: turn paging OFF (default ON)\n");
			printf("-l57: set line length to 57 (default 0)\n");
			printf("-fxyz: set output file name to xyz (default no"
				" file)\n");
			break;

		case 'v':	/* turn verbose output on */
			flags |= VERBOSE;
			break;
		case 'i':	/* turn case sensitivity on */
			flags |= CASE_INSENSITIVE;
			break;
		case 'p':	/* turn paging off */
			flags &= ~PAGING;
			break;
		case 'l':	/* set line length */
			scan_switch_number(c, &line_length);
			break;
		case 'f':	/* set output file name */
			output_file_name = optarg;
			break;
		case ':':
			fprintf(stderr, "Missing parameter to switch '%c'\n",
				optopt);
			break;
		case '?':
			fprintf(stderr, "Illegal switch '%c'\n", optopt);
			break;
		}	/* switch */
	}

	/* for purposes of demonstration, print out final values of options */
	printf("\nfinal values of all options:\n");

	print_flag(flags, VERBOSE, "verbose");
	print_flag(flags, CASE_INSENSITIVE, "case-insensitive");
	print_flag(flags, PAGING, "paging");

	printf("\t%19s: %d\n", "line_length", line_length);

	printf("\t%19s: \"%s\"\n", "output_file_name",
		(output_file_name != NULL) ? output_file_name : "");

	/* now process all the remaining command line parameters */
	if (optind < argc ) {
		printf("\nnon-option command line parameters\n\n");
		for( ;  optind < argc;  optind++ ) {
			printf("%2d: %s\n", optind, argv[optind]);
		}
	}

	return EXIT_SUCCESS;
}	/* main */

/* vi: set autoindent tabstop=8 shiftwidth=8 : */
