#
# Makefile for the sample subdirectory.
#


obj-m +=  my_module.o
my_module-objs := sample.o

obj-m +=  my_module2.o
my_module2-objs := sample2.o

obj-m +=  my_module3.o
my_module3-objs := sample3.o

